import { useShopStore } from './store/store';
import { normalizeLanguage, preferenceLocale } from './data/preferences';

const en = {
  loading: 'Loading your lists…', addItem: 'Add item', close: 'Close', dismiss: 'Dismiss',
  undo: 'Undo', removed: 'Removed {name}', dismissUndo: 'Dismiss undo', shareCurrent: 'Share current list',
  openSettings: 'Open settings', manageLists: 'Switch or manage lists', lists: 'Lists', editBudget: 'Edit budget',
  budgetOptional: 'Budget (optional)', budget: 'Budget', save: 'Save', viewOnly: 'View only',
  welcome: 'Welcome to CoShop', welcomeText: 'Tap the + button to add your first item. Search the catalog or just type — we’ll file it under the right aisle automatically.',
  addFirst: 'Add my first item', shoppingProgress: 'Shopping progress', progressCount: '{done} of {total}',
  progressAria: '{done} of {total} items purchased', pending: 'Pending', purchased: 'Purchased',
  allInCart: 'All items in cart. Nice shopping!', addAnother: 'Add another item', clearPurchased: 'Clear purchased items',
  emptyTitle: 'Your list is empty', emptyText: 'Tap the + button to add your first item. CoShop works offline, so you can shop anywhere.',
  addFirstShort: 'Add first item', emptyShared: 'This shared list does not have any items yet.', clear: 'Clear', settings: 'Settings', regionFormatting: 'Region & formatting',
  regionHelp: 'Controls language, dates, number formatting, and the currency used by new lists.', region: 'Region',
  language: 'Language', languageHelp: 'The interface changes immediately. You can change this at any time.', currency: 'Currency',
  currencyEditableHelp: 'Updates this list and becomes the default for new lists.', currencyViewHelp: 'Sets the default for new lists; this shared list is view only.',
  accountBackup: 'Account & backup', accountHelp: 'Guest lists stay on this device. Sign in only for backup, sync, and shared lists.',
  localMode: 'Local mode', localModeHelp: 'Cloud backup has not been configured. Your lists still work offline.',
  automaticBackup: 'Automatic backup on', signOut: 'Sign out', syncing: 'Syncing…', backedUp: 'Backed up', readySync: 'Ready to sync', syncNow: 'Sync now',
  yourData: 'Your data', dataHelp: 'Export lists and item details at any time.', downloadExport: 'Download JSON export',
  exportIncludes: 'Includes lists, items, stores, and preferences.', privacyNotice: 'Privacy notice', export: 'Export', verifiedAccount: 'Verified account',
  addItemTitle: 'Add Item', addItemDialog: 'Add a new item', itemName: 'Item name', searchProducts: 'Search products, e.g. bananas',
  filedUnder: 'Will be filed under {category}', hideDetails: 'Hide details', addPriceQuantity: 'Add price or quantity',
  unitPrice: 'Unit price (optional)', quantity: 'Qty', addToList: 'Add to list',
  manageListsDialog: 'Manage lists', yourLists: 'Your Lists', listName: 'List name', saveName: 'Save name',
  renameList: 'Rename {name}', duplicateList: 'Duplicate {name}', deleteList: 'Delete {name}', keepOneList: 'Keep at least one list',
  ownerDeleteOnly: 'Only the list owner can delete this shared list', deleteListTitle: 'Delete list', newListName: 'New list name (optional)',
  newListNameAria: 'New list name', new: 'New', storeFor: 'Store for “{name}” (optional)', storeExample: 'e.g. Tesco, Carrefour', storeName: 'Store name',
  markPending: 'Mark as pending', markPurchased: 'Mark as purchased', viewPhoto: 'View photo', addPhoto: 'Add photo',
  moreActions: 'More actions for {name}', editItem: 'Edit item', removeItem: 'Remove item', photoFor: 'Photo for {name}',
  photoHelp: 'Snap a photo or pick an image to remember the exact brand.', savePhoto: 'Save photo', itemPhoto: 'Item Photo', addPhotoTitle: 'Add Photo', replace: 'Replace', choosePhoto: 'Choose photo', remove: 'Remove', imageError: 'Could not read this image.', editItemTitle: 'Edit Item',
  name: 'Name', category: 'Category', priceOptional: 'Price (optional)', saveChanges: 'Save changes', categoryAria: 'Category: {category}',
  partialEstimate: 'Partial estimate · {missing} of {total} {items} missing a price', item: 'item', items: 'items',
  budgetUsed: '{used} of {budget} budget used', inCart: 'In Cart', knownTotal: 'Known total', estimated: 'Estimated', remaining: 'Remaining', overBy: 'Over by',
  shareTitle: 'Share “{name}”', shareIntro: 'Invite someone to this list only. CoShop will not request your contacts or see who you message.',
  sharingUnavailable: 'Cloud sharing is not configured for this deployment.', shareSignIn: 'Sign in to create a revocable invitation. Your existing list will be preserved.',
  viewOnlyShare: 'You have view-only access. Ask a list editor to create an invitation.', accessLevel: 'Access level', canEdit: 'Can edit',
  canEditHelp: 'Add, change, and check off items', viewOnlyHelp: 'See the list without changing it', creatingLink: 'Creating secure link…', createLink: 'Create invitation link',
  invitationReady: 'Invitation ready', singleUse: 'Single use · expires {date}', shareApps: 'Messages, WhatsApp & more', copyLink: 'Copy link', copied: 'Copied',
  phoneSms: 'Phone number for SMS', optional: 'optional', openSms: 'Open SMS', phonePrivacy: 'The number stays in this form and is not uploaded.', invitationLink: 'Invitation link', createInviteError: 'Could not create the invitation.', copiedNotice: 'Invitation link copied.', copyFailed: 'Copy failed. Select and copy the link below.', shareMenuFailed: 'Your share menu could not be opened. The link is still available below.', nativeShareTitle: 'Join “{name}” in CoShop', nativeShareRole: 'Join as {role}.', inviteMessage: 'Join my “{name}” shopping list in CoShop as {role}: {url}', roleAnEditor: 'an editor', roleAViewer: 'a viewer',
  email: 'Email', phone: 'Phone', signInMethod: 'Sign-in method', emailSignIn: 'Email for a secure sign-in link', sendLink: 'Send link',
  mobileNumber: 'Mobile number, including country code', phoneSignInPrivacy: 'Your number is used for sign-in verification and is never shared with list owners.',
  resendIn: 'Resend in {seconds}s', sendCode: 'Send {channel} code', verificationCode: 'Verification code', verify: 'Verify', checkEmail: 'Check your email for a secure sign-in link. Your lists will remain here.', codeSent: 'Code sent by {channel}.', phoneVerified: 'Phone number verified.', resendAvailable: 'Resend available in {seconds}s', sendAnotherCode: 'Send another code',
  checkingInvitation: 'Checking invitation…', invitationUnavailable: 'Invitation unavailable', invalidInvitation: 'This link is invalid, expired, revoked, or has already been used.', openCoShop: 'Open CoShop', invitationExpires: 'Invitation expires {date}.', checkInviteError: 'Invitation could not be checked.', acceptInviteError: 'The invitation could not be accepted.',
  invitedTo: 'You’ve been invited to “{name}”', inviteRole: '{role} access · invitation expires {date}', claimInvite: 'Sign in to claim this invitation. CoShop will preserve any lists already on this device, and the inviter will not receive your email or phone number.',
  signedInAs: 'You are signed in as {account}. Only this shopping list will be shared.', joining: 'Joining list…', joinAs: 'Join as {role}', notNow: 'Not now — open my lists',
  roleEditor: 'editor', roleViewer: 'viewer', refreshNeeded: 'CoShop needs a refresh', refreshSafe: 'Your lists are stored on this device and have not been removed.', reloadSafely: 'Reload safely',
  importPdf: 'Import PDF', importInvoice: 'Import shopping invoice', importIntro: 'Choose a text-based PDF invoice. It is read on this device; personal and payment details are not uploaded.',
  importLanguage: 'Imported item language', keepOriginal: 'Keep original language', choosePdf: 'Choose PDF invoice', parsingPdf: 'Reading page {page} of {total}…',
  importSummary: '{products} products · {units} units · {pages} pages', importedListName: 'New list name', includePrices: 'Include historical unit prices',
  aiEnrichment: 'AI categorization & translation', aiPrivacy: 'Only product names, EANs, and retailer departments are sent. The PDF and personal details stay on this device.',
  enrichWithAi: 'Categorize & translate', categorizeWithAi: 'Categorize with AI', enrichingItems: 'Improving {count} products…', aiSignInRequired: 'Sign in from Settings to use AI enrichment. You can still review and import the locally parsed list.',
  aiComplete: 'AI enrichment complete. Review names and low-confidence items before importing.', sourceCategory: 'Retailer category', confidenceLow: 'Check category',
  selectAll: 'Select all', selectNone: 'Select none', importSelected: 'Import {count} products', noProductsSelected: 'Select at least one product.',
  pdfLimits: 'PDF only · up to 10 MB and 20 pages', productQuantity: 'Quantity {quantity}', historicalPrice: 'Historical price {price}',
  categoryFruits: 'Fruits', categoryVegetables: 'Vegetables', categoryDairy: 'Dairy & Eggs', categoryMeat: 'Meat & Seafood', categoryBakery: 'Bakery',
  categoryPantry: 'Pantry', categoryFrozen: 'Frozen', categoryBeverages: 'Beverages', categorySnacks: 'Snacks', categoryBreakfast: 'Breakfast',
  categoryHousehold: 'Household', categoryPersonal: 'Personal Care', categoryBaby: 'Baby', categoryPet: 'Pet', categoryOther: 'Other',
} as const;

type MessageKey = keyof typeof en;
type Vars = Record<string, string | number>;

const fr: Partial<Record<MessageKey, string>> = {
  refreshNeeded: 'CoShop doit être actualisé', refreshSafe: 'Vos listes sont stockées sur cet appareil et n’ont pas été supprimées.', reloadSafely: 'Actualiser en toute sécurité',
  emptyShared: 'Cette liste partagée ne contient pas encore d’articles.', clear: 'Effacer', checkEmail: 'Consultez votre e-mail pour ouvrir le lien sécurisé. Vos listes resteront ici.', codeSent: 'Code envoyé par {channel}.', phoneVerified: 'Numéro vérifié.', resendAvailable: 'Nouvel envoi possible dans {seconds} s', sendAnotherCode: 'Envoyer un autre code', invitationExpires: 'L’invitation expire le {date}.', checkInviteError: 'Impossible de vérifier l’invitation.', acceptInviteError: 'Impossible d’accepter l’invitation.',
  loading: 'Chargement de vos listes…', addItem: 'Ajouter un article', close: 'Fermer', dismiss: 'Ignorer', undo: 'Annuler', removed: '{name} supprimé',
  dismissUndo: 'Fermer le message d’annulation', shareCurrent: 'Partager la liste actuelle', openSettings: 'Ouvrir les paramètres', manageLists: 'Changer ou gérer les listes', lists: 'Listes', editBudget: 'Modifier le budget', budgetOptional: 'Budget (facultatif)', budget: 'Budget', save: 'Enregistrer', viewOnly: 'Lecture seule',
  welcome: 'Bienvenue sur CoShop', welcomeText: 'Touchez le bouton + pour ajouter votre premier article. Recherchez dans le catalogue ou saisissez simplement son nom — nous le classerons automatiquement dans le bon rayon.', addFirst: 'Ajouter mon premier article', importPdf: 'Importer un PDF',
  shoppingProgress: 'Progression des courses', progressCount: '{done} sur {total}', progressAria: '{done} articles achetés sur {total}', pending: 'À acheter', purchased: 'Achetés', allInCart: 'Tous les articles sont dans le panier. Bonnes courses !', addAnother: 'Ajouter un autre article', clearPurchased: 'Effacer les articles achetés', emptyTitle: 'Votre liste est vide', emptyText: 'Touchez le bouton + pour ajouter votre premier article. CoShop fonctionne hors ligne, où que vous soyez.', addFirstShort: 'Ajouter un article',
  settings: 'Paramètres', regionFormatting: 'Région et formats', regionHelp: 'Définit la langue, les dates, les nombres et la devise des nouvelles listes.', region: 'Région', language: 'Langue', languageHelp: 'L’interface change immédiatement. Vous pouvez modifier ce choix à tout moment.', currency: 'Devise', currencyEditableHelp: 'Met à jour cette liste et devient la valeur par défaut des nouvelles listes.', currencyViewHelp: 'Définit la devise des nouvelles listes ; cette liste partagée est en lecture seule.',
  accountBackup: 'Compte et sauvegarde', accountHelp: 'Les listes invité restent sur cet appareil. Connectez-vous uniquement pour les sauvegarder, les synchroniser et les partager.', localMode: 'Mode local', localModeHelp: 'La sauvegarde cloud n’est pas configurée. Vos listes fonctionnent toujours hors ligne.', automaticBackup: 'Sauvegarde automatique activée', signOut: 'Se déconnecter', syncing: 'Synchronisation…', backedUp: 'Sauvegardé', readySync: 'Prêt à synchroniser', syncNow: 'Synchroniser maintenant',
  yourData: 'Vos données', dataHelp: 'Exportez vos listes et leurs articles à tout moment.', downloadExport: 'Télécharger l’export JSON', exportIncludes: 'Contient les listes, articles, magasins et préférences.', privacyNotice: 'Avis de confidentialité', export: 'Exporter', verifiedAccount: 'Compte vérifié',
  addItemTitle: 'Ajouter un article', addItemDialog: 'Ajouter un nouvel article', itemName: 'Nom de l’article', searchProducts: 'Rechercher un produit, par ex. bananes', filedUnder: 'Classé dans {category}', hideDetails: 'Masquer les détails', addPriceQuantity: 'Ajouter un prix ou une quantité', unitPrice: 'Prix unitaire (facultatif)', quantity: 'Qté', addToList: 'Ajouter à la liste',
  manageListsDialog: 'Gérer les listes', yourLists: 'Vos listes', listName: 'Nom de la liste', saveName: 'Enregistrer le nom', renameList: 'Renommer {name}', duplicateList: 'Dupliquer {name}', deleteList: 'Supprimer {name}', keepOneList: 'Conservez au moins une liste', ownerDeleteOnly: 'Seul le propriétaire peut supprimer cette liste partagée', deleteListTitle: 'Supprimer la liste', newListName: 'Nom de la nouvelle liste (facultatif)', newListNameAria: 'Nom de la nouvelle liste', new: 'Nouvelle', storeFor: 'Magasin pour « {name} » (facultatif)', storeExample: 'par ex. Carrefour, Monoprix', storeName: 'Nom du magasin',
  markPending: 'Marquer comme à acheter', markPurchased: 'Marquer comme acheté', viewPhoto: 'Voir la photo', addPhoto: 'Ajouter une photo', moreActions: 'Plus d’actions pour {name}', editItem: 'Modifier l’article', removeItem: 'Supprimer l’article', photoFor: 'Photo de {name}', photoHelp: 'Prenez une photo ou choisissez une image pour mémoriser la marque exacte.', savePhoto: 'Enregistrer la photo', itemPhoto: 'Photo de l’article', addPhotoTitle: 'Ajouter une photo', replace: 'Remplacer', choosePhoto: 'Choisir une photo', remove: 'Supprimer', imageError: 'Impossible de lire cette image.', editItemTitle: 'Modifier l’article', name: 'Nom', category: 'Catégorie', priceOptional: 'Prix (facultatif)', saveChanges: 'Enregistrer les modifications', categoryAria: 'Catégorie : {category}',
  partialEstimate: 'Estimation partielle · prix manquant pour {missing} {items} sur {total}', item: 'article', items: 'articles', budgetUsed: '{used} utilisés sur un budget de {budget}', inCart: 'Dans le panier', knownTotal: 'Total connu', estimated: 'Estimé', remaining: 'Restant', overBy: 'Dépassement',
  shareTitle: 'Partager « {name} »', shareIntro: 'Invitez une personne uniquement à cette liste. CoShop ne demandera pas vos contacts et ne verra pas vos messages.', sharingUnavailable: 'Le partage cloud n’est pas configuré pour ce déploiement.', shareSignIn: 'Connectez-vous pour créer une invitation révocable. Votre liste actuelle sera conservée.', viewOnlyShare: 'Vous avez un accès en lecture seule. Demandez à un éditeur de créer une invitation.', accessLevel: 'Niveau d’accès', canEdit: 'Modification autorisée', canEditHelp: 'Ajouter, modifier et cocher des articles', viewOnlyHelp: 'Voir la liste sans la modifier', creatingLink: 'Création du lien sécurisé…', createLink: 'Créer un lien d’invitation', invitationReady: 'Invitation prête', singleUse: 'Usage unique · expire le {date}', shareApps: 'Messages, WhatsApp et plus', copyLink: 'Copier le lien', copied: 'Copié', phoneSms: 'Numéro de téléphone pour SMS', optional: 'facultatif', openSms: 'Ouvrir les SMS', phonePrivacy: 'Le numéro reste dans ce formulaire et n’est pas envoyé.', invitationLink: 'Lien d’invitation',
  createInviteError: 'Impossible de créer l’invitation.', copiedNotice: 'Lien d’invitation copié.', copyFailed: 'Échec de la copie. Sélectionnez et copiez le lien ci-dessous.', shareMenuFailed: 'Impossible d’ouvrir le menu de partage. Le lien reste disponible ci-dessous.', nativeShareTitle: 'Rejoindre « {name} » sur CoShop', nativeShareRole: 'Rejoindre comme {role}.', inviteMessage: 'Rejoignez ma liste de courses « {name} » sur CoShop comme {role} : {url}', roleAnEditor: 'éditeur', roleAViewer: 'lecteur', email: 'E-mail', phone: 'Téléphone', signInMethod: 'Mode de connexion', emailSignIn: 'E-mail pour recevoir un lien de connexion sécurisé', sendLink: 'Envoyer le lien', mobileNumber: 'Numéro de mobile avec indicatif pays', phoneSignInPrivacy: 'Votre numéro sert à vérifier la connexion et n’est jamais partagé avec les propriétaires de listes.', resendIn: 'Renvoyer dans {seconds} s', sendCode: 'Envoyer le code par {channel}', verificationCode: 'Code de vérification', verify: 'Vérifier',
  checkingInvitation: 'Vérification de l’invitation…', invitationUnavailable: 'Invitation indisponible', invalidInvitation: 'Ce lien est invalide, expiré, révoqué ou a déjà été utilisé.', openCoShop: 'Ouvrir CoShop', invitedTo: 'Vous êtes invité à « {name} »', inviteRole: 'Accès {role} · invitation valable jusqu’au {date}', claimInvite: 'Connectez-vous pour accepter cette invitation. CoShop conservera les listes déjà présentes sur cet appareil, et l’expéditeur ne recevra ni votre e-mail ni votre numéro.', signedInAs: 'Vous êtes connecté en tant que {account}. Seule cette liste de courses sera partagée.', joining: 'Ajout à la liste…', joinAs: 'Rejoindre comme {role}', notNow: 'Pas maintenant — ouvrir mes listes', roleEditor: 'éditeur', roleViewer: 'lecteur',
  categoryFruits: 'Fruits', categoryVegetables: 'Légumes', categoryDairy: 'Produits laitiers et œufs', categoryMeat: 'Viandes et poissons', categoryBakery: 'Boulangerie', categoryPantry: 'Épicerie', categoryFrozen: 'Surgelés', categoryBeverages: 'Boissons', categorySnacks: 'En-cas', categoryBreakfast: 'Petit-déjeuner', categoryHousehold: 'Maison', categoryPersonal: 'Hygiène et soins', categoryBaby: 'Bébé', categoryPet: 'Animaux', categoryOther: 'Autres',
};

const de: Partial<Record<MessageKey, string>> = {
  refreshNeeded: 'CoShop muss neu geladen werden', refreshSafe: 'Deine Listen sind auf diesem Gerät gespeichert und wurden nicht entfernt.', reloadSafely: 'Sicher neu laden',
  emptyShared: 'Diese geteilte Liste enthält noch keine Artikel.', clear: 'Leeren', checkEmail: 'Prüfe deine E-Mails auf den sicheren Anmeldelink. Deine Listen bleiben hier.', codeSent: 'Code per {channel} gesendet.', phoneVerified: 'Telefonnummer bestätigt.', resendAvailable: 'Erneut senden in {seconds} s', sendAnotherCode: 'Weiteren Code senden', invitationExpires: 'Die Einladung läuft am {date} ab.', checkInviteError: 'Die Einladung konnte nicht geprüft werden.', acceptInviteError: 'Die Einladung konnte nicht angenommen werden.',
  loading: 'Listen werden geladen…', addItem: 'Artikel hinzufügen', close: 'Schließen', dismiss: 'Ausblenden', undo: 'Rückgängig', removed: '{name} entfernt', shareCurrent: 'Aktuelle Liste teilen', openSettings: 'Einstellungen öffnen', manageLists: 'Listen wechseln oder verwalten', lists: 'Listen', editBudget: 'Budget bearbeiten', budgetOptional: 'Budget (optional)', budget: 'Budget', save: 'Speichern', viewOnly: 'Nur ansehen',
  welcome: 'Willkommen bei CoShop', welcomeText: 'Tippe auf +, um deinen ersten Artikel hinzuzufügen. Durchsuche den Katalog oder tippe einfach den Namen ein — wir ordnen ihn automatisch dem richtigen Bereich zu.', addFirst: 'Meinen ersten Artikel hinzufügen', importPdf: 'PDF importieren', shoppingProgress: 'Einkaufsfortschritt', progressCount: '{done} von {total}', progressAria: '{done} von {total} Artikeln gekauft', pending: 'Offen', purchased: 'Gekauft', allInCart: 'Alle Artikel sind im Warenkorb. Viel Spaß beim Einkaufen!', addAnother: 'Weiteren Artikel hinzufügen', clearPurchased: 'Gekaufte Artikel entfernen', emptyTitle: 'Deine Liste ist leer', emptyText: 'Tippe auf +, um deinen ersten Artikel hinzuzufügen. CoShop funktioniert offline, damit du überall einkaufen kannst.', addFirstShort: 'Ersten Artikel hinzufügen',
  settings: 'Einstellungen', regionFormatting: 'Region und Formatierung', regionHelp: 'Steuert Sprache, Datum, Zahlenformat und die Währung neuer Listen.', region: 'Region', language: 'Sprache', languageHelp: 'Die Oberfläche wechselt sofort. Du kannst dies jederzeit ändern.', currency: 'Währung', currencyEditableHelp: 'Aktualisiert diese Liste und wird zum Standard für neue Listen.', currencyViewHelp: 'Legt den Standard für neue Listen fest; diese geteilte Liste ist schreibgeschützt.', accountBackup: 'Konto und Sicherung', accountHelp: 'Gastlisten bleiben auf diesem Gerät. Melde dich nur für Sicherung, Synchronisierung und geteilte Listen an.', localMode: 'Lokaler Modus', localModeHelp: 'Cloud-Sicherung ist nicht eingerichtet. Deine Listen funktionieren weiterhin offline.', automaticBackup: 'Automatische Sicherung aktiv', signOut: 'Abmelden', syncing: 'Synchronisierung…', backedUp: 'Gesichert', readySync: 'Bereit zum Synchronisieren', syncNow: 'Jetzt synchronisieren', yourData: 'Deine Daten', dataHelp: 'Exportiere Listen und Artikeldetails jederzeit.', downloadExport: 'JSON-Export herunterladen', exportIncludes: 'Enthält Listen, Artikel, Geschäfte und Einstellungen.', privacyNotice: 'Datenschutzhinweis', export: 'Exportieren', verifiedAccount: 'Verifiziertes Konto',
  addItemTitle: 'Artikel hinzufügen', addItemDialog: 'Neuen Artikel hinzufügen', itemName: 'Artikelname', searchProducts: 'Produkte suchen, z. B. Bananen', filedUnder: 'Wird unter {category} abgelegt', hideDetails: 'Details ausblenden', addPriceQuantity: 'Preis oder Menge hinzufügen', unitPrice: 'Stückpreis (optional)', quantity: 'Anz.', addToList: 'Zur Liste hinzufügen', manageListsDialog: 'Listen verwalten', yourLists: 'Deine Listen', listName: 'Listenname', saveName: 'Namen speichern', renameList: '{name} umbenennen', duplicateList: '{name} duplizieren', deleteList: '{name} löschen', keepOneList: 'Mindestens eine Liste behalten', ownerDeleteOnly: 'Nur der Eigentümer kann diese geteilte Liste löschen', deleteListTitle: 'Liste löschen', newListName: 'Name der neuen Liste (optional)', newListNameAria: 'Name der neuen Liste', new: 'Neu', storeFor: 'Geschäft für „{name}“ (optional)', storeExample: 'z. B. Aldi, Rewe', storeName: 'Name des Geschäfts',
  markPending: 'Als offen markieren', markPurchased: 'Als gekauft markieren', viewPhoto: 'Foto ansehen', addPhoto: 'Foto hinzufügen', moreActions: 'Weitere Aktionen für {name}', editItem: 'Artikel bearbeiten', removeItem: 'Artikel entfernen', photoFor: 'Foto für {name}', photoHelp: 'Mache ein Foto oder wähle ein Bild, um dir die genaue Marke zu merken.', savePhoto: 'Foto speichern', itemPhoto: 'Artikelfoto', addPhotoTitle: 'Foto hinzufügen', replace: 'Ersetzen', choosePhoto: 'Foto auswählen', remove: 'Entfernen', imageError: 'Dieses Bild konnte nicht gelesen werden.', editItemTitle: 'Artikel bearbeiten', name: 'Name', category: 'Kategorie', priceOptional: 'Preis (optional)', saveChanges: 'Änderungen speichern', categoryAria: 'Kategorie: {category}', partialEstimate: 'Teilschätzung · bei {missing} von {total} {items} fehlt ein Preis', item: 'Artikel', items: 'Artikeln', budgetUsed: '{used} von {budget} Budget verwendet', inCart: 'Im Wagen', knownTotal: 'Bekannte Summe', estimated: 'Geschätzt', remaining: 'Verbleibend', overBy: 'Darüber',
  shareTitle: '„{name}“ teilen', shareIntro: 'Lade jemanden nur zu dieser Liste ein. CoShop fragt nicht nach deinen Kontakten und sieht nicht, wem du schreibst.', sharingUnavailable: 'Cloud-Freigabe ist für diese Bereitstellung nicht eingerichtet.', shareSignIn: 'Melde dich an, um eine widerrufbare Einladung zu erstellen. Deine vorhandene Liste bleibt erhalten.', viewOnlyShare: 'Du hast nur Lesezugriff. Bitte einen Bearbeiter, eine Einladung zu erstellen.', accessLevel: 'Zugriffsebene', canEdit: 'Darf bearbeiten', canEditHelp: 'Artikel hinzufügen, ändern und abhaken', viewOnlyHelp: 'Liste ansehen, ohne sie zu ändern', creatingLink: 'Sicherer Link wird erstellt…', createLink: 'Einladungslink erstellen', invitationReady: 'Einladung bereit', singleUse: 'Einmalig · läuft am {date} ab', shareApps: 'Nachrichten, WhatsApp und mehr', copyLink: 'Link kopieren', copied: 'Kopiert', phoneSms: 'Telefonnummer für SMS', optional: 'optional', openSms: 'SMS öffnen', phonePrivacy: 'Die Nummer bleibt in diesem Formular und wird nicht hochgeladen.', invitationLink: 'Einladungslink',
  createInviteError: 'Die Einladung konnte nicht erstellt werden.', copiedNotice: 'Einladungslink kopiert.', copyFailed: 'Kopieren fehlgeschlagen. Wähle den Link unten aus und kopiere ihn.', shareMenuFailed: 'Das Teilen-Menü konnte nicht geöffnet werden. Der Link ist unten weiterhin verfügbar.', nativeShareTitle: '„{name}“ in CoShop beitreten', nativeShareRole: 'Als {role} beitreten.', inviteMessage: 'Tritt meiner Einkaufsliste „{name}“ in CoShop als {role} bei: {url}', roleAnEditor: 'Bearbeiter', roleAViewer: 'Betrachter', email: 'E-Mail', phone: 'Telefon', signInMethod: 'Anmeldemethode', emailSignIn: 'E-Mail für einen sicheren Anmeldelink', sendLink: 'Link senden', mobileNumber: 'Mobilnummer mit Ländervorwahl', phoneSignInPrivacy: 'Deine Nummer wird zur Anmeldung geprüft und nie mit Listeneigentümern geteilt.', resendIn: 'Erneut senden in {seconds} s', sendCode: '{channel}-Code senden', verificationCode: 'Bestätigungscode', verify: 'Bestätigen', checkingInvitation: 'Einladung wird geprüft…', invitationUnavailable: 'Einladung nicht verfügbar', invalidInvitation: 'Dieser Link ist ungültig, abgelaufen, widerrufen oder wurde bereits verwendet.', openCoShop: 'CoShop öffnen', invitedTo: 'Du wurdest zu „{name}“ eingeladen', inviteRole: '{role}-Zugriff · Einladung läuft am {date} ab', claimInvite: 'Melde dich an, um diese Einladung anzunehmen. CoShop behält alle Listen auf diesem Gerät; der Einladende erhält weder deine E-Mail noch deine Telefonnummer.', signedInAs: 'Du bist als {account} angemeldet. Nur diese Einkaufsliste wird geteilt.', joining: 'Liste wird beigetreten…', joinAs: 'Als {role} beitreten', notNow: 'Nicht jetzt — meine Listen öffnen', roleEditor: 'Bearbeiter', roleViewer: 'Betrachter',
  categoryFruits: 'Obst', categoryVegetables: 'Gemüse', categoryDairy: 'Milchprodukte & Eier', categoryMeat: 'Fleisch & Fisch', categoryBakery: 'Backwaren', categoryPantry: 'Vorräte', categoryFrozen: 'Tiefkühlkost', categoryBeverages: 'Getränke', categorySnacks: 'Snacks', categoryBreakfast: 'Frühstück', categoryHousehold: 'Haushalt', categoryPersonal: 'Körperpflege', categoryBaby: 'Baby', categoryPet: 'Haustier', categoryOther: 'Sonstiges',
};

const es: Partial<Record<MessageKey, string>> = {
  refreshNeeded: 'CoShop necesita recargarse', refreshSafe: 'Tus listas están guardadas en este dispositivo y no se han eliminado.', reloadSafely: 'Recargar de forma segura',
  emptyShared: 'Esta lista compartida aún no tiene artículos.', clear: 'Borrar', checkEmail: 'Revisa tu correo para abrir el enlace seguro. Tus listas permanecerán aquí.', codeSent: 'Código enviado por {channel}.', phoneVerified: 'Número de teléfono verificado.', resendAvailable: 'Podrás reenviar en {seconds} s', sendAnotherCode: 'Enviar otro código', invitationExpires: 'La invitación caduca el {date}.', checkInviteError: 'No se pudo comprobar la invitación.', acceptInviteError: 'No se pudo aceptar la invitación.',
  loading: 'Cargando tus listas…', addItem: 'Añadir artículo', close: 'Cerrar', dismiss: 'Descartar', undo: 'Deshacer', removed: '{name} eliminado', shareCurrent: 'Compartir la lista actual', openSettings: 'Abrir ajustes', manageLists: 'Cambiar o gestionar listas', lists: 'Listas', editBudget: 'Editar presupuesto', budgetOptional: 'Presupuesto (opcional)', budget: 'Presupuesto', save: 'Guardar', viewOnly: 'Solo lectura',
  welcome: 'Te damos la bienvenida a CoShop', welcomeText: 'Pulsa + para añadir tu primer artículo. Busca en el catálogo o escribe su nombre — lo clasificaremos automáticamente en la sección adecuada.', addFirst: 'Añadir mi primer artículo', importPdf: 'Importar PDF', shoppingProgress: 'Progreso de la compra', progressCount: '{done} de {total}', progressAria: '{done} de {total} artículos comprados', pending: 'Pendientes', purchased: 'Comprados', allInCart: 'Todos los artículos están en el carrito. ¡Buena compra!', addAnother: 'Añadir otro artículo', clearPurchased: 'Borrar artículos comprados', emptyTitle: 'Tu lista está vacía', emptyText: 'Pulsa + para añadir tu primer artículo. CoShop funciona sin conexión para que compres donde quieras.', addFirstShort: 'Añadir primer artículo',
  settings: 'Ajustes', regionFormatting: 'Región y formato', regionHelp: 'Controla el idioma, las fechas, los números y la moneda de las listas nuevas.', region: 'Región', language: 'Idioma', languageHelp: 'La interfaz cambia inmediatamente. Puedes modificarlo en cualquier momento.', currency: 'Moneda', currencyEditableHelp: 'Actualiza esta lista y será la opción predeterminada para las listas nuevas.', currencyViewHelp: 'Define la moneda de las listas nuevas; esta lista compartida es de solo lectura.', accountBackup: 'Cuenta y copia de seguridad', accountHelp: 'Las listas de invitado permanecen en este dispositivo. Inicia sesión solo para hacer copias, sincronizar y compartir listas.', localMode: 'Modo local', localModeHelp: 'La copia en la nube no está configurada. Tus listas siguen funcionando sin conexión.', automaticBackup: 'Copia automática activada', signOut: 'Cerrar sesión', syncing: 'Sincronizando…', backedUp: 'Copia guardada', readySync: 'Listo para sincronizar', syncNow: 'Sincronizar ahora', yourData: 'Tus datos', dataHelp: 'Exporta listas y detalles de artículos en cualquier momento.', downloadExport: 'Descargar exportación JSON', exportIncludes: 'Incluye listas, artículos, tiendas y preferencias.', privacyNotice: 'Aviso de privacidad', export: 'Exportar', verifiedAccount: 'Cuenta verificada',
  addItemTitle: 'Añadir artículo', addItemDialog: 'Añadir un artículo nuevo', itemName: 'Nombre del artículo', searchProducts: 'Buscar productos, p. ej. plátanos', filedUnder: 'Se clasificará en {category}', hideDetails: 'Ocultar detalles', addPriceQuantity: 'Añadir precio o cantidad', unitPrice: 'Precio unitario (opcional)', quantity: 'Cant.', addToList: 'Añadir a la lista', manageListsDialog: 'Gestionar listas', yourLists: 'Tus listas', listName: 'Nombre de la lista', saveName: 'Guardar nombre', renameList: 'Cambiar nombre de {name}', duplicateList: 'Duplicar {name}', deleteList: 'Eliminar {name}', keepOneList: 'Conserva al menos una lista', ownerDeleteOnly: 'Solo el propietario puede eliminar esta lista compartida', deleteListTitle: 'Eliminar lista', newListName: 'Nombre de lista nueva (opcional)', newListNameAria: 'Nombre de lista nueva', new: 'Nueva', storeFor: 'Tienda para «{name}» (opcional)', storeExample: 'p. ej. Mercadona, Carrefour', storeName: 'Nombre de la tienda',
  markPending: 'Marcar como pendiente', markPurchased: 'Marcar como comprado', viewPhoto: 'Ver foto', addPhoto: 'Añadir foto', moreActions: 'Más acciones para {name}', editItem: 'Editar artículo', removeItem: 'Eliminar artículo', photoFor: 'Foto de {name}', photoHelp: 'Haz una foto o elige una imagen para recordar la marca exacta.', savePhoto: 'Guardar foto', itemPhoto: 'Foto del artículo', addPhotoTitle: 'Añadir foto', replace: 'Reemplazar', choosePhoto: 'Elegir foto', remove: 'Eliminar', imageError: 'No se ha podido leer esta imagen.', editItemTitle: 'Editar artículo', name: 'Nombre', category: 'Categoría', priceOptional: 'Precio (opcional)', saveChanges: 'Guardar cambios', categoryAria: 'Categoría: {category}', partialEstimate: 'Estimación parcial · faltan precios en {missing} de {total} {items}', item: 'artículo', items: 'artículos', budgetUsed: '{used} usados de un presupuesto de {budget}', inCart: 'En el carrito', knownTotal: 'Total conocido', estimated: 'Estimado', remaining: 'Restante', overBy: 'Exceso',
  shareTitle: 'Compartir «{name}»', shareIntro: 'Invita a alguien solo a esta lista. CoShop no solicitará tus contactos ni verá a quién escribes.', sharingUnavailable: 'La función de compartir en la nube no está configurada.', shareSignIn: 'Inicia sesión para crear una invitación revocable. Tu lista actual se conservará.', viewOnlyShare: 'Tienes acceso de solo lectura. Pide a un editor que cree una invitación.', accessLevel: 'Nivel de acceso', canEdit: 'Puede editar', canEditHelp: 'Añadir, cambiar y marcar artículos', viewOnlyHelp: 'Ver la lista sin cambiarla', creatingLink: 'Creando enlace seguro…', createLink: 'Crear enlace de invitación', invitationReady: 'Invitación lista', singleUse: 'Un solo uso · caduca el {date}', shareApps: 'Mensajes, WhatsApp y más', copyLink: 'Copiar enlace', copied: 'Copiado', phoneSms: 'Número de teléfono para SMS', optional: 'opcional', openSms: 'Abrir SMS', phonePrivacy: 'El número permanece en este formulario y no se carga.', invitationLink: 'Enlace de invitación',
  createInviteError: 'No se ha podido crear la invitación.', copiedNotice: 'Enlace de invitación copiado.', copyFailed: 'No se pudo copiar. Selecciona y copia el enlace de abajo.', shareMenuFailed: 'No se pudo abrir el menú para compartir. El enlace sigue disponible abajo.', nativeShareTitle: 'Únete a «{name}» en CoShop', nativeShareRole: 'Únete como {role}.', inviteMessage: 'Únete a mi lista de compras «{name}» en CoShop como {role}: {url}', roleAnEditor: 'editor', roleAViewer: 'lector', email: 'Correo', phone: 'Teléfono', signInMethod: 'Método de acceso', emailSignIn: 'Correo para recibir un enlace de acceso seguro', sendLink: 'Enviar enlace', mobileNumber: 'Número de móvil con prefijo internacional', phoneSignInPrivacy: 'Tu número se usa para verificar el acceso y nunca se comparte con propietarios de listas.', resendIn: 'Reenviar en {seconds} s', sendCode: 'Enviar código por {channel}', verificationCode: 'Código de verificación', verify: 'Verificar', checkingInvitation: 'Comprobando invitación…', invitationUnavailable: 'Invitación no disponible', invalidInvitation: 'Este enlace no es válido, ha caducado, se ha revocado o ya se ha utilizado.', openCoShop: 'Abrir CoShop', invitedTo: 'Te han invitado a «{name}»', inviteRole: 'Acceso de {role} · la invitación caduca el {date}', claimInvite: 'Inicia sesión para aceptar la invitación. CoShop conservará las listas de este dispositivo y quien invita no recibirá tu correo ni tu teléfono.', signedInAs: 'Has iniciado sesión como {account}. Solo se compartirá esta lista de compras.', joining: 'Uniéndote a la lista…', joinAs: 'Unirse como {role}', notNow: 'Ahora no — abrir mis listas', roleEditor: 'editor', roleViewer: 'lector',
  categoryFruits: 'Frutas', categoryVegetables: 'Verduras', categoryDairy: 'Lácteos y huevos', categoryMeat: 'Carne y pescado', categoryBakery: 'Panadería', categoryPantry: 'Despensa', categoryFrozen: 'Congelados', categoryBeverages: 'Bebidas', categorySnacks: 'Aperitivos', categoryBreakfast: 'Desayuno', categoryHousehold: 'Hogar', categoryPersonal: 'Cuidado personal', categoryBaby: 'Bebé', categoryPet: 'Mascotas', categoryOther: 'Otros',
};

const dictionaries: Record<string, Partial<Record<MessageKey, string>>> = { en, fr, de, es };

export const translate = (language: string, key: MessageKey, vars: Vars = {}): string => {
  const template = dictionaries[normalizeLanguage(language)]?.[key] ?? en[key];
  return Object.entries(vars).reduce((value, [name, replacement]) => value.split(`{${name}}`).join(String(replacement)), template);
};

export const categoryKey = (id: string): MessageKey => ({
  'produce-fruit': 'categoryFruits', 'produce-veg': 'categoryVegetables', 'dairy-eggs': 'categoryDairy',
  'meat-seafood': 'categoryMeat', bakery: 'categoryBakery', pantry: 'categoryPantry', frozen: 'categoryFrozen',
  beverages: 'categoryBeverages', snacks: 'categorySnacks', breakfast: 'categoryBreakfast', household: 'categoryHousehold',
  'personal-care': 'categoryPersonal', baby: 'categoryBaby', pet: 'categoryPet', other: 'categoryOther',
}[id] as MessageKey ?? 'categoryOther');

export function useI18n() {
  const preferences = useShopStore((state) => state.preferences);
  const language = normalizeLanguage(preferences.language);
  return {
    language,
    locale: preferenceLocale(language, preferences.region),
    t: (key: MessageKey, vars?: Vars) => translate(language, key, vars),
    categoryLabel: (id: string) => translate(language, categoryKey(id)),
  };
}
